<?php

/**
 * BaseLogs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $usuario_id
 * @property string $username
 * @property string $ip
 * @property string $proxy
 * @property boolean $estado
 * @property datetime $fecha_creacion
 * 
 * @method integer  getId()             Returns the current record's "id" value
 * @method integer  getUsuarioId()      Returns the current record's "usuario_id" value
 * @method string   getUsername()       Returns the current record's "username" value
 * @method string   getIp()             Returns the current record's "ip" value
 * @method string   getProxy()          Returns the current record's "proxy" value
 * @method boolean  getEstado()         Returns the current record's "estado" value
 * @method datetime getFechaCreacion()  Returns the current record's "fecha_creacion" value
 * @method Logs     setId()             Sets the current record's "id" value
 * @method Logs     setUsuarioId()      Sets the current record's "usuario_id" value
 * @method Logs     setUsername()       Sets the current record's "username" value
 * @method Logs     setIp()             Sets the current record's "ip" value
 * @method Logs     setProxy()          Sets the current record's "proxy" value
 * @method Logs     setEstado()         Sets the current record's "estado" value
 * @method Logs     setFechaCreacion()  Sets the current record's "fecha_creacion" value
 * 
 * @package    Yonohagofila
 * @subpackage model
 * @author     Arquitectura - Juan Pablo Cardona Mejia <jpcardona@ibccodecontrol.com> - Desarrollo - Jeison Pira Murillo <jpira@ibccodecontrol.com> - Diseño - Ricardo Piedrahita <rpiedrahita.america@solucionesc2.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLogs extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('logs');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('usuario_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('username', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('ip', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('proxy', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('estado', 'boolean', null, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('fecha_creacion', 'datetime', null, array(
             'type' => 'datetime',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}