<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Perfil', 'doctrine');

/**
 * BasePerfil
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property integer $id_usuario
 * @property timestamp $fecha_creacion
 * @property timestamp $fecha_actualizacion
 * @property Doctrine_Collection $PerfilCredencial
 * @property Doctrine_Collection $Usuario
 * 
 * @method integer             getId()                  Returns the current record's "id" value
 * @method string              getNombre()              Returns the current record's "nombre" value
 * @method integer             getIdUsuario()           Returns the current record's "id_usuario" value
 * @method timestamp           getFechaCreacion()       Returns the current record's "fecha_creacion" value
 * @method timestamp           getFechaActualizacion()  Returns the current record's "fecha_actualizacion" value
 * @method Doctrine_Collection getPerfilCredencial()    Returns the current record's "PerfilCredencial" collection
 * @method Doctrine_Collection getUsuario()             Returns the current record's "Usuario" collection
 * @method Perfil              setId()                  Sets the current record's "id" value
 * @method Perfil              setNombre()              Sets the current record's "nombre" value
 * @method Perfil              setIdUsuario()           Sets the current record's "id_usuario" value
 * @method Perfil              setFechaCreacion()       Sets the current record's "fecha_creacion" value
 * @method Perfil              setFechaActualizacion()  Sets the current record's "fecha_actualizacion" value
 * @method Perfil              setPerfilCredencial()    Sets the current record's "PerfilCredencial" collection
 * @method Perfil              setUsuario()             Sets the current record's "Usuario" collection
 * 
 * @package    Yonohagofila
 * @subpackage model
 * @author     Arquitectura - Juan Pablo Cardona Mejia <jpcardona@ibccodecontrol.com> - Desarrollo - Jeison Pira Murillo <jpira@ibccodecontrol.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePerfil extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('perfil');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('id_usuario', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_creacion', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('fecha_actualizacion', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PerfilCredencial', array(
             'local' => 'id',
             'foreign' => 'perfil_id'));

        $this->hasMany('Usuario', array(
             'local' => 'id',
             'foreign' => 'perfil_id'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'nombre',
             ),
             'length' => 110,
             'canUpdate' => true,
             ));
        $this->actAs($sluggable0);
    }
}