<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UsuarioBloqueado', 'doctrine');

/**
 * BaseUsuarioBloqueado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $usuario_id
 * @property integer $local_id
 * @property timestamp $fecha_creacion
 * @property integer $id_usuario
 * @property Local $Local
 * @property Usuario $Usuario
 * 
 * @method integer          getId()             Returns the current record's "id" value
 * @method integer          getUsuarioId()      Returns the current record's "usuario_id" value
 * @method integer          getLocalId()        Returns the current record's "local_id" value
 * @method timestamp        getFechaCreacion()  Returns the current record's "fecha_creacion" value
 * @method integer          getIdUsuario()      Returns the current record's "id_usuario" value
 * @method Local            getLocal()          Returns the current record's "Local" value
 * @method Usuario          getUsuario()        Returns the current record's "Usuario" value
 * @method UsuarioBloqueado setId()             Sets the current record's "id" value
 * @method UsuarioBloqueado setUsuarioId()      Sets the current record's "usuario_id" value
 * @method UsuarioBloqueado setLocalId()        Sets the current record's "local_id" value
 * @method UsuarioBloqueado setFechaCreacion()  Sets the current record's "fecha_creacion" value
 * @method UsuarioBloqueado setIdUsuario()      Sets the current record's "id_usuario" value
 * @method UsuarioBloqueado setLocal()          Sets the current record's "Local" value
 * @method UsuarioBloqueado setUsuario()        Sets the current record's "Usuario" value
 * 
 * @package    Yonohagofila
 * @subpackage model
 * @author     Arquitectura - Juan Pablo Cardona Mejia <jpcardona@ibccodecontrol.com> - Desarrollo - Jeison Pira Murillo <jpira@ibccodecontrol.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsuarioBloqueado extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuario_bloqueado');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('usuario_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('local_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_creacion', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('id_usuario', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Local', array(
             'local' => 'local_id',
             'foreign' => 'id'));

        $this->hasOne('Usuario', array(
             'local' => 'usuario_id',
             'foreign' => 'id'));
    }
}