<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Estadistica', 'doctrine');

/**
 * BaseEstadistica
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $usuario_id
 * @property Usuario $Usuario
 * 
 * @method integer     getId()         Returns the current record's "id" value
 * @method integer     getUsuarioId()  Returns the current record's "usuario_id" value
 * @method Usuario     getUsuario()    Returns the current record's "Usuario" value
 * @method Estadistica setId()         Sets the current record's "id" value
 * @method Estadistica setUsuarioId()  Sets the current record's "usuario_id" value
 * @method Estadistica setUsuario()    Sets the current record's "Usuario" value
 * 
 * @package    yonohagofila_sf1.4
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstadistica extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estadistica');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('usuario_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Usuario', array(
             'local' => 'usuario_id',
             'foreign' => 'id'));
    }
}