<?php

/**
 * BaseEventos_Local
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property integer $local_id
 * @property integer $tipoevento_id
 * @property integer $id_usuario
 * @property datetime $fecha_evento
 * @property datetime $fecha_creacion
 * @property Local $Local
 * @property Tipos_Eventos $Tipos_Eventos
 * 
 * @method integer       getId()             Returns the current record's "id" value
 * @method string        getNombre()         Returns the current record's "nombre" value
 * @method integer       getLocalId()        Returns the current record's "local_id" value
 * @method integer       getTipoeventoId()   Returns the current record's "tipoevento_id" value
 * @method integer       getIdUsuario()      Returns the current record's "id_usuario" value
 * @method datetime      getFechaEvento()    Returns the current record's "fecha_evento" value
 * @method datetime      getFechaCreacion()  Returns the current record's "fecha_creacion" value
 * @method Local         getLocal()          Returns the current record's "Local" value
 * @method Tipos_Eventos getTiposEventos()   Returns the current record's "Tipos_Eventos" value
 * @method Eventos_Local setId()             Sets the current record's "id" value
 * @method Eventos_Local setNombre()         Sets the current record's "nombre" value
 * @method Eventos_Local setLocalId()        Sets the current record's "local_id" value
 * @method Eventos_Local setTipoeventoId()   Sets the current record's "tipoevento_id" value
 * @method Eventos_Local setIdUsuario()      Sets the current record's "id_usuario" value
 * @method Eventos_Local setFechaEvento()    Sets the current record's "fecha_evento" value
 * @method Eventos_Local setFechaCreacion()  Sets the current record's "fecha_creacion" value
 * @method Eventos_Local setLocal()          Sets the current record's "Local" value
 * @method Eventos_Local setTiposEventos()   Sets the current record's "Tipos_Eventos" value
 * 
 * @package    Yonohagofila
 * @subpackage model
 * @author     Arquitectura - Juan Pablo Cardona Mejia <jpcardona@ibccodecontrol.com> - Desarrollo - Jeison Pira Murillo <jpira@ibccodecontrol.com> - Diseño - Ricardo Piedrahita <rpiedrahita.america@solucionesc2.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEventos_Local extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('eventoslocal');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('local_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('tipoevento_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_usuario', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_evento', 'datetime', null, array(
             'type' => 'datetime',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
        $this->hasColumn('fecha_creacion', 'datetime', null, array(
             'type' => 'datetime',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Local', array(
             'local' => 'local_id',
             'foreign' => 'id'));

        $this->hasOne('Tipos_Eventos', array(
             'local' => 'tipoevento_id',
             'foreign' => 'id'));
    }
}