<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PerfilCredencial', 'doctrine');

/**
 * BasePerfilCredencial
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $perfil_id
 * @property integer $credencial_id
 * @property integer $id_usuario
 * @property timestamp $fecha_creacion
 * @property Perfil $Perfil
 * @property Credencial $Credencial
 * 
 * @method integer          getPerfilId()       Returns the current record's "perfil_id" value
 * @method integer          getCredencialId()   Returns the current record's "credencial_id" value
 * @method integer          getIdUsuario()      Returns the current record's "id_usuario" value
 * @method timestamp        getFechaCreacion()  Returns the current record's "fecha_creacion" value
 * @method Perfil           getPerfil()         Returns the current record's "Perfil" value
 * @method Credencial       getCredencial()     Returns the current record's "Credencial" value
 * @method PerfilCredencial setPerfilId()       Sets the current record's "perfil_id" value
 * @method PerfilCredencial setCredencialId()   Sets the current record's "credencial_id" value
 * @method PerfilCredencial setIdUsuario()      Sets the current record's "id_usuario" value
 * @method PerfilCredencial setFechaCreacion()  Sets the current record's "fecha_creacion" value
 * @method PerfilCredencial setPerfil()         Sets the current record's "Perfil" value
 * @method PerfilCredencial setCredencial()     Sets the current record's "Credencial" value
 * 
 * @package    Yonohagofila
 * @subpackage model
 * @author     Arquitectura - Juan Pablo Cardona Mejia <jpcardona@ibccodecontrol.com> - Desarrollo - Jeison Pira Murillo <jpira@ibccodecontrol.com> - Diseño - Ricardo Piedrahita <rpiedrahita.america@solucionesc2.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePerfilCredencial extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('perfil_credencial');
        $this->hasColumn('perfil_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('credencial_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_usuario', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_creacion', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Perfil', array(
             'local' => 'perfil_id',
             'foreign' => 'id'));

        $this->hasOne('Credencial', array(
             'local' => 'credencial_id',
             'foreign' => 'id'));
    }
}