<?php

/**
 * BaseTipos_Eventos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property integer $id_usuario
 * @property datetime $fecha_creacion
 * @property datetime $fecha_actualizacion
 * @property Doctrine_Collection $Eventos_Local
 * 
 * @method integer             getId()                  Returns the current record's "id" value
 * @method string              getNombre()              Returns the current record's "nombre" value
 * @method integer             getIdUsuario()           Returns the current record's "id_usuario" value
 * @method datetime            getFechaCreacion()       Returns the current record's "fecha_creacion" value
 * @method datetime            getFechaActualizacion()  Returns the current record's "fecha_actualizacion" value
 * @method Doctrine_Collection getEventosLocal()        Returns the current record's "Eventos_Local" collection
 * @method Tipos_Eventos       setId()                  Sets the current record's "id" value
 * @method Tipos_Eventos       setNombre()              Sets the current record's "nombre" value
 * @method Tipos_Eventos       setIdUsuario()           Sets the current record's "id_usuario" value
 * @method Tipos_Eventos       setFechaCreacion()       Sets the current record's "fecha_creacion" value
 * @method Tipos_Eventos       setFechaActualizacion()  Sets the current record's "fecha_actualizacion" value
 * @method Tipos_Eventos       setEventosLocal()        Sets the current record's "Eventos_Local" collection
 * 
 * @package    Yonohagofila
 * @subpackage model
 * @author     Arquitectura - Juan Pablo Cardona Mejia <jpcardona@ibccodecontrol.com> - Desarrollo - Jeison Pira Murillo <jpira@ibccodecontrol.com> - Diseño - Ricardo Piedrahita <rpiedrahita.america@solucionesc2.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipos_Eventos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tiposeventos');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('id_usuario', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha_creacion', 'datetime', null, array(
             'type' => 'datetime',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('fecha_actualizacion', 'datetime', null, array(
             'type' => 'datetime',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Eventos_Local', array(
             'local' => 'id',
             'foreign' => 'tipoevento_id'));
    }
}