<?php

/**
 * AlarmaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AlarmaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AlarmaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Alarma');
    }
}