<?php

/**
 * CredencialTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CredencialTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CredencialTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Credencial');
    }
}