<?php

/**
 * EstadisticaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstadisticaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstadisticaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Estadistica');
    }
}