<?php

/**
 * Eventos_LocalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Eventos_LocalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Eventos_LocalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Eventos_Local');
    }
}