<?php

/**
 * Horario_atencionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Horario_atencionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Horario_atencionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Horario_atencion');
    }
}