<?php

/**
 * LogsAccessTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LogsAccessTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LogsAccessTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LogsAccess');
    }
}