<?php

/**
 * PerfilCredencialTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PerfilCredencialTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PerfilCredencialTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PerfilCredencial');
    }
}