<?php

/**
 * PreregistroTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PreregistroTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PreregistroTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Preregistro');
    }
}