<?php

/**
 * PromedioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PromedioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PromedioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Promedio');
    }
}