<?php

/**
 * RankingUsuarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RankingUsuarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RankingUsuarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RankingUsuario');
    }
}