<?php

/**
 * RankingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RankingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RankingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ranking');
    }
}