<?php

/**
 * Tipos_EventosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Tipos_EventosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Tipos_EventosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tipos_Eventos');
    }
}