<?php

/**
 * Tipos_Eventos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Yonohagofila
 * @subpackage model
 * @author     Arquitectura - Juan Pablo Cardona Mejia <jpcardona@ibccodecontrol.com> - Desarrollo - Jeison Pira Murillo <jpira@ibccodecontrol.com> - Diseño - Ricardo Piedrahita <rpiedrahita.america@solucionesc2.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Tipos_Eventos extends BaseTipos_Eventos
{
    public function __toString() {
        return $this->nombre;
    }

}