<?php

/**
 * UsuarioBloqueadoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsuarioBloqueadoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsuarioBloqueadoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UsuarioBloqueado');
    }
}