generator:
  class: sfDoctrineGenerator
  param:
    model_class:           horario_atencion
    theme:                 yonohagofila
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          horario_atencion
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:  
        title: Horarios Por Local
        display: [ horario, local_id ]
      filter:  
        display: [ horario, local_id ]
      form:    ~
      edit:  
        display: [ horario, local_id ]
      new:     
        display: [ horario, local_id ]
