generator:
  class: sfDoctrineGenerator
  param:
    model_class:           eventos_local
    theme:                 yonohagofila
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          eventos_local
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields: 
        fecha_actualizacion: { label: Fecha Evento }
      list: 
        title: Eventos de Local
        display: [ nombre, local, tipoevento, fecha_actualizacion ] 
      filter:
        display: [ nombre, local_id, tipoevento_id, fecha_actualizacion ]
      form:    ~
      edit:    ~
      new:     ~
