generator:
  class: sfDoctrineGenerator
  param:
    model_class:           ranking
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          ranking
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list: 
        display: [ nombre, fecha_creacion ]
      filter:
        display: [ nombre, fecha_creacion ]
      form:    ~
      edit:    ~
      new:     ~
