    
Credencial:
  connection: doctrine
  tableName: credencial
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    id_usuario:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    fecha_creacion:
      type: datetime
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    fecha_actualizacion:
      type: datetime
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  actAs:
    Sluggable:
      unique: true
      fields: [nombre]
      length: 110
      canUpdate: true  
  relations:
    PerfilCredencial:
      local: id
      foreign: credencial_id
      type: many 
              
      
Perfil:
  connection: doctrine
  tableName: perfil
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    nombre:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    id_usuario:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    fecha_creacion:
      type: datetime
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    fecha_actualizacion:
      type: datetime
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  actAs:
    Sluggable:
      unique: true
      fields: [nombre]
      length: 110
      canUpdate: true
  relations:
    PerfilCredencial:
      local: id
      foreign: perfil_id
      type: many
    Usuario:
      local: id
      foreign: perfil_id
      type: many
      
      
PerfilCredencial:
  connection: doctrine
  tableName: perfil_credencial
  columns:
    perfil_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    credencial_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    id_usuario:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    fecha_creacion:
      type: datetime
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  relations:
    Perfil:
      local: perfil_id
      foreign: id
      type: one
    Credencial:
      local: credencial_id
      foreign: id
      type: one
           
      
Usuario:
  connection: doctrine
  tableName: usuario
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    perfil_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    email:
      type: string(150)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    contrasena:
      type: string(150)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    nombre:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    tipo_identificacion:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    identificacion:
      type: string(100)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    foto:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    estado:
      type: integer(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    token:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    fecha_nacimiento:
      type: datetime
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    fecha_creacion:
      type: datetime
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
  actAs:
    Sluggable:
      unique: true
      fields: [email]
      length: 160
      canUpdate: true
  relations:
    Perfil:
      local: perfil_id
      foreign: id
      type: one
    Estadistica:
      local: id
      foreign: usuario_id
      type: many
    RankingUsuario:
      local: id
      foreign: usuario_id
      type: many
    UsuarioBloqueado:
      local: id
      foreign: usuario_id
      type: many
             
            
Logs:
  tableName: logs
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true  
    usuario_id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    username:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
    ip:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
    proxy:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: false    
    estado:
      type: boolean
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    fecha_creacion:
      type: datetime
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
      

Documentos:
  tableName: documentos
  columns:
    id:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: true
    empresa:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    no_carpeta:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    tomo:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    año:
      type: string(255)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    id_usuario:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
    fecha_creacion:
      type: datetime
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    fecha_actualizacion:
      type: datetime
      fixed: false
      unsigned: false
      primary: false
      notnull: false
      autoincrement: false
  