generator:
  class: sfDoctrineGenerator
  param:
    model_class:           tipos_eventos
    theme:                 yonohagofila
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tipos_eventos
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list: 
        title: Tipos de Eventos
        display: [ nombre, fecha_creacion ]
      filter: 
        display: [ nombre ]
      form:    ~
      edit:
        display: [ nombre ]
      new:  
         display: [ nombre ]
